-- MySQL Script generated by MySQL Workbench
-- 11/24/16 10:30:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gonenpru
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gonenpru
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gonenpru` DEFAULT CHARACTER SET utf8 ;
USE `gonenpru` ;

-- -----------------------------------------------------
-- Table `gonenpru`.`Passengers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gonenpru`.`Passengers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `email` VARCHAR(64) NULL,
  `password` BLOB NULL,
  `salt` BLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gonenpru`.`Controllers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gonenpru`.`Controllers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `email` VARCHAR(64) NULL,
  `password` BLOB NULL,
  `salt` BLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gonenpru`.`Airlines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gonenpru`.`Airlines` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` BLOB NULL,
  `salt` BLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gonenpru`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gonenpru`.`Employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` BLOB NULL,
  `salt` BLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gonenpru`.`Manufacturers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gonenpru`.`Manufacturers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gonenpru`.`Plane_Models`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gonenpru`.`Plane_Models` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `max_passengers` INT NULL,
  `Manufacturer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Plane_Models_Manufacturers_idx` (`Manufacturer_id` ASC),
  CONSTRAINT `fk_Plane_Models_Manufacturers`
    FOREIGN KEY (`Manufacturer_id`)
    REFERENCES `gonenpru`.`Manufacturers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gonenpru`.`Plane_Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gonenpru`.`Plane_Status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gonenpru`.`Planes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gonenpru`.`Planes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Plane_Model_id` INT NOT NULL,
  `Plane_Status_id` INT NOT NULL,
  `Airline_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Planes_Plane_Models1_idx` (`Plane_Model_id` ASC),
  INDEX `fk_Planes_Plane_Status1_idx` (`Plane_Status_id` ASC),
  INDEX `fk_Planes_Airlines1_idx` (`Airline_id` ASC),
  CONSTRAINT `fk_Planes_Plane_Models1`
    FOREIGN KEY (`Plane_Model_id`)
    REFERENCES `gonenpru`.`Plane_Models` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Planes_Plane_Status1`
    FOREIGN KEY (`Plane_Status_id`)
    REFERENCES `gonenpru`.`Plane_Status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Planes_Airlines1`
    FOREIGN KEY (`Airline_id`)
    REFERENCES `gonenpru`.`Airlines` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gonenpru`.`Plane_Movements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gonenpru`.`Plane_Movements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `posX` INT NULL,
  `posY` INT NULL,
  `dirX` INT NULL,
  `dirY` INT NULL,
  `Plane_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Plane_Movements_Planes1_idx` (`Plane_id` ASC),
  CONSTRAINT `fk_Plane_Movements_Planes1`
    FOREIGN KEY (`Plane_id`)
    REFERENCES `gonenpru`.`Planes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gonenpru`.`Terminals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gonenpru`.`Terminals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gonenpru`.`Gates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gonenpru`.`Gates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `Terminal_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Gates_Terminals1_idx` (`Terminal_id` ASC),
  CONSTRAINT `fk_Gates_Terminals1`
    FOREIGN KEY (`Terminal_id`)
    REFERENCES `gonenpru`.`Terminals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gonenpru`.`Baggages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gonenpru`.`Baggages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `Terminal_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Baggages_Terminals1_idx` (`Terminal_id` ASC),
  CONSTRAINT `fk_Baggages_Terminals1`
    FOREIGN KEY (`Terminal_id`)
    REFERENCES `gonenpru`.`Terminals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gonenpru`.`Routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gonenpru`.`Routes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `detination` VARCHAR(45) NULL,
  `origin` VARCHAR(45) NULL,
  `departure` VARCHAR(45) NULL,
  `arrival` VARCHAR(45) NULL,
  `Airline_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Routes_Airlines1_idx` (`Airline_id` ASC),
  CONSTRAINT `fk_Routes_Airlines1`
    FOREIGN KEY (`Airline_id`)
    REFERENCES `gonenpru`.`Airlines` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gonenpru`.`Flights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gonenpru`.`Flights` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `duration` INT NULL,
  `delay` INT NULL,
  `date_departure` DATE NULL,
  `date_arrival` DATE NULL,
  `Route_id` INT NOT NULL,
  `Plane_id` INT NOT NULL,
  `Gate_id` INT NOT NULL,
  `Baggage_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Flights_Routes1_idx` (`Route_id` ASC),
  INDEX `fk_Flights_Planes1_idx` (`Plane_id` ASC),
  INDEX `fk_Flights_Gates1_idx` (`Gate_id` ASC),
  INDEX `fk_Flights_Baggages1_idx` (`Baggage_id` ASC),
  CONSTRAINT `fk_Flights_Routes1`
    FOREIGN KEY (`Route_id`)
    REFERENCES `gonenpru`.`Routes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flights_Planes1`
    FOREIGN KEY (`Plane_id`)
    REFERENCES `gonenpru`.`Planes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flights_Gates1`
    FOREIGN KEY (`Gate_id`)
    REFERENCES `gonenpru`.`Gates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flights_Baggages1`
    FOREIGN KEY (`Baggage_id`)
    REFERENCES `gonenpru`.`Baggages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gonenpru`.`Tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gonenpru`.`Tickets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NULL,
  `Flight_id` INT NOT NULL,
  `Passenger_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Tickets_Flights1_idx` (`Flight_id` ASC),
  INDEX `fk_Tickets_Passengers1_idx` (`Passenger_id` ASC),
  CONSTRAINT `fk_Tickets_Flights1`
    FOREIGN KEY (`Flight_id`)
    REFERENCES `gonenpru`.`Flights` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tickets_Passengers1`
    FOREIGN KEY (`Passenger_id`)
    REFERENCES `gonenpru`.`Passengers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
